// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rain33.Models;

namespace Rain33.Migrations
{
    [DbContext(typeof(NoviceContext))]
    [Migration("20190405165237_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rain33.Models.Novice", b =>
                {
                    b.Property<int>("NoviceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UporabnikiId");

                    b.Property<string>("avtor");

                    b.Property<string>("besedilo");

                    b.Property<DateTime>("datum");

                    b.HasKey("NoviceId");

                    b.HasIndex("UporabnikiId");

                    b.ToTable("Novica");
                });

            modelBuilder.Entity("Rain33.Models.Uporabniki", b =>
                {
                    b.Property<int>("UporabnikiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Roles");

                    b.Property<string>("password");

                    b.Property<string>("salt");

                    b.Property<string>("username");

                    b.HasKey("UporabnikiId");

                    b.ToTable("Uporabnik");
                });

            modelBuilder.Entity("Rain33.Models.Novice", b =>
                {
                    b.HasOne("Rain33.Models.Uporabniki", "Uporabniki")
                        .WithMany("Novice")
                        .HasForeignKey("UporabnikiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
